Teenager Validation
Intellisavvy/teens_portal_react_app pull request #35
Opened 2022-08-29 11:47 UTC by Hareesh-7

2022-08-30 04:40 UTC, mani-intellisavvy requested changes

2022-08-30 04:40 UTC, mani-intellisavvy commented on .env
> +REACT_APP_DOMINE_NAME = "dev-intellisavvy-teen.us.auth0.com"
we should not add .env file to githug

2022-08-30 04:55 UTC, Hareesh-7 commented on .env
> +REACT_APP_DOMINE_NAME = "dev-intellisavvy-teen.us.auth0.com"
Added into gitignore file

2022-09-02 02:14 UTC, mani-intellisavvy requested changes

2022-09-02 02:14 UTC, mani-intellisavvy commented on src/lib/utils.ts
> +    const mailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]{2,3}$/i;
call existing method from utils instead of writing logic in the component

2022-09-02 02:16 UTC, mani-intellisavvy requested changes

2022-09-02 02:16 UTC, mani-intellisavvy commented on src/lib/utilities.tsx
> -    const name= "^[A-Za-z]+$";
move this validations logic to utils. So that we can use them in other components

2022-09-02 02:16 UTC, mani-intellisavvy commented on src/lib/utils.ts
> -    const password="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{7})";
same here. move all regular expression related validations to utils file. So that we can have all the validations in a single place and easy to maintain

2022-09-02 04:11 UTC, closed without merging

2022-09-02 04:11 UTC, mani-intellisavvy commented
all the code available in another branch. so declining this PR